# Generated by Blocky to Godot. Atlas was 64x64 (4x4 tiles); extended to
# 64x80 (4x5) locally to add torch/bed tiles — see world.gd's TORCH/BED
# block support. Tiles are 16x16.
class_name BlockAtlas

const COLS := 4
const ROWS := 5
const TILE := 16

const INDEX := {
	"grass_top": 0,
	"grass_side": 1,
	"grass_bottom": 2,
	"dirt": 3,
	"stone": 4,
	"sand": 5,
	"log_top": 6,
	"log_side": 7,
	"leaves": 8,
	"snow": 9,
	"planks": 10,
	"workbench_top": 11,
	"workbench_side": 12,
	"coal_ore": 13,
	"iron_ore": 14,
	"water_surface": 15,
	"torch_top": 16,
	"torch_side": 17,
	"bed_top": 18,
	"bed_side": 19,
}

# UV rect for a face, in 0..1 atlas space.
static func uv(face: String) -> Rect2:
	var i: int = INDEX[face]
	var c := i % COLS
	var r := i / COLS
	return Rect2(float(c) / COLS, float(r) / ROWS, 1.0 / COLS, 1.0 / ROWS)

# Per-block face map: [top, side, bottom]
const FACES := {
	"grass": ["grass_top", "grass_side", "grass_bottom"],
	"dirt": ["dirt", "dirt", "dirt"],
	"stone": ["stone", "stone", "stone"],
	"sand": ["sand", "sand", "sand"],
	"log": ["log_top", "log_side", "log_top"],
	"leaves": ["leaves", "leaves", "leaves"],
	"snow": ["snow", "snow", "snow"],
	"planks": ["planks", "planks", "planks"],
	"workbench": ["workbench_top", "workbench_side", "planks"],
	"coal_ore": ["coal_ore", "coal_ore", "coal_ore"],
	"iron_ore": ["iron_ore", "iron_ore", "iron_ore"],
	"water": ["water_surface", "water_surface", "water_surface"],
	"torch": ["torch_top", "torch_side", "planks"],
	"bed": ["bed_top", "bed_side", "planks"],
}
